### ISSUE TITLE
General Info abt Abdul Sir udemy DSA

### ISSUE THREAD

**Issue by A-R-M-028** [Anuragmaurya-code/Data-Structures#1]
_Hey Anuragmaurya i'm ashikur, I found you from discussion section of abdul bari sir udemy course. Here is a question i want to know that you posted some topics from the courses it it complete or there is still some that you have not uploaded yet._
Really glad to let me know back!
Thanks man

**Comment by Anuragmaurya-code** [comment]
The topics on which the notes are uploaded is complete but they are a few topics that aren't completed yet which will be completed sooner or later as only a few are pending
